apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  NETWORK: "testnet"
  WEB3_PROVIDER: "ipc"
  LOG_LEVEL: "debug"
  DB_HOST: "joy-plus-db-mysql-master-0.joy-plus-db-mysql.default.svc.cluster.local"
  DB_DATABASE: "joy_plus"
