apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  NETWORK: "testnet"
  WEB3_PROVIDER: "ipc"
  LOG_LEVEL: "debug"
  DB_HOST: "10.100.254.158"
  DB_DATABASE: "joy_plus_testnet"
