# Default values for joy-plus-db.
# This is a YAML-formatted file.
# Uses bitnami/mysql chart (https://hub.kubeapps.com/charts/bitnami/mysql).

image:
  tag: 8.0.18

db:
  name: joy_plus

# root:
  # password: passed by command line

# replication:
  # password: passed by command line

master:
  persistence:
    mountPath: /mysql
    size: 8Gi

slave:
  replicas: 2
  persistence:
    mountPath: /mysql
    size: 8Gi
