apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-joy-plus-backend
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - wallet.joy.plus
      secretName: joy.plus-tls
  rules:
    - host: wallet.joy.plus
      http:
        paths:
          - path: /
            backend:
              serviceName: joy-plus-backend
              servicePort: 5555
