apiVersion: v1
kind: Service
metadata:
  name: {{ include "explorer-mainnet.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "explorer-mainnet.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "explorer-mainnet.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
